trigger:
  branches:
    include:
      - main
  paths:
    include:
      - "src"

pool:
  vmImage: "windows-latest"

variables:
  major: 1
  minor: 0
  patch: 0
  version: $(major).$(minor).$(patch)

name: $(major).$(minor).$(patch)$(Rev:.r)

steps:

- task: UseDotNet@2
  displayName: 'Install .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.x'

# Restore NuGet packages
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: 'src/AzDoAgentScaler.csproj'

# Build project in Release mode
- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: 'src/AzDoAgentScaler.csproj'
    arguments: '-c Release'

# Publish for Windows (win-x64)
- task: DotNetCoreCLI@2
  displayName: 'Publish for Windows (win-x64)'
  inputs:
    command: 'publish'
    projects: '$(Build.SourcesDirectory)/src/AzDoAgentScaler.csproj'
    publishWebProjects: false
    zipAfterPublish: false
    arguments: > 
      -c Release
      -p:PublishSingleFile=true
      -p:SelfContained=true
      -p:Version=$(version)
      -p:FileVersion=$(Build.BuildNumber)
      -p:AssemblyVersion=$(version)
      -p:InformationalVersion=$(Build.SourceBranchName)-$(version)
      -r win-x64
      -o $(Build.ArtifactStagingDirectory)/win-x64

# Publish for Linux (linux-x64)
- task: DotNetCoreCLI@2
  displayName: 'Publish for Linux (linux-x64)'
  inputs:
    command: 'publish'
    projects: '$(Build.SourcesDirectory)/src/AzDoAgentScaler.csproj'
    publishWebProjects: false
    zipAfterPublish: false
    arguments: > 
      -c Release
      -p:PublishSingleFile=true
      -p:SelfContained=true
      -p:Version=$(version)
      -p:FileVersion=$(Build.BuildNumber)
      -p:AssemblyVersion=$(version)
      -p:InformationalVersion=$(Build.SourceBranchName)-$(version)
      -r linux-x64
      -o $(Build.ArtifactStagingDirectory)/linux-x64

# Publish for macOS (osx-x64)
- task: DotNetCoreCLI@2
  displayName: 'Publish for macOS (osx-x64)'
  inputs:
    command: 'publish'
    projects: '$(Build.SourcesDirectory)/src/AzDoAgentScaler.csproj'
    publishWebProjects: false
    zipAfterPublish: false
    arguments: > 
      -c Release
      -p:PublishSingleFile=true
      -p:SelfContained=true
      -p:Version=$(version)
      -p:FileVersion=$(Build.BuildNumber)
      -p:AssemblyVersion=$(version)
      -p:InformationalVersion=$(Build.SourceBranchName)-$(version)
      -r osx-x64
      -o $(Build.ArtifactStagingDirectory)/osx-x64

# Publish all artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts for all Runtimes'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'PublishedExecutables'
    publishLocation: 'Container'
